# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [49]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [50]:
A = np.arange(1, 16).reshape(3,5)
print(A)
print(A.ndim)
print(A.shape)
print (A.size)
print(A.dtype.name)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [51]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(B-C)
print()
print(B*C)
print()
print(B@C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [59]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()
print("Exponentiate each number elementwise:")
print(np.exp(B))
print()

print("Calculate the minimum value in the whole matrix:")
print(B.min())
print()

print("Calculate the minimum value in each row")
print(B.min(axis=0))
print()

print("Calculate the minimum value in each column:")
print (B.min(axis=1))
print()

print("Find the index value for the minimum value in the whole matrix")
print(np.argmin(B))
print()

print("Find the index value for the minimum value in each row")
print(np.argmin(B, axis=0))
print()

print("Calculate the sum for all elements:")
print(B.sum())
print()

print("Calculate the mean for each column")
print(np.mean(B, axis=1))
print()
print("Calculate the median for each column")
print(np.median(B, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiate each number elementwise:
[[   2.71828183    7.3890561    20.08553692]
 [  54.59815003  148.4131591   403.42879349]
 [1096.63315843 2980.95798704 8103.08392758]]

Calculate the minimum value in the whole matrix:
1

Calculate the minimum value in each row
[1 2 3]

Calculate the minimum value in each column:
[1 4 7]

Find the index value for the minimum value in the whole matrix
0

Find the index value for the minimum value in each row
[0 0 0]

Calculate the sum for all elements:
45

Calculate the mean for each column
[2. 5. 8.]

Calculate the median for each column
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [5]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
A[1]


array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
#The missing indicies will be considered complete slices (the above example shows index row 1 and all the column values for that row)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [7]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
for i in A:
    print(i)
print()
for i in A.flat: 
    print (i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [9]:
a = np.arange(30) #a is a 1d matrix with the elements 0, 1, 2..... 30
b = a.reshape(2, 3, -1) 
#b reshapes a to a three dimensional matrix with two 3x5 matrices. 
#2 refers to the two 3x5 matrices, 3 refers to the 3 rows in each matrix and -1 lets pyhton calculate the 
#amount of columns to each matrix to fit all the elements, which is 5
#we can change the -1 to a 5 and get the same result 
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [10]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [61]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [62]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [63]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [64]:
def add_mult_matrices (matrix_a, matrix_b, add_or_multiply):
    if not (isinstance(matrix_a, np.ndarray) and isinstance(matrix_b, np.ndarray)):
        raise TypeError("Inputs must be of the type numpy.ndarrays")

    if add_or_multiply == "add":
        if not matrix_a.shape == matrix_b.shape:
            raise ValueError ("Matrices must have the same size")
        else:
            return matrix_a + matrix_b
    
    elif add_or_multiply == "multiply":
        if not matrix_a.shape[1] == matrix_b.shape[0]:
            raise ValueError ("Matrices sizes do not conform for multiplication")
        else:
            return matrix_a @ matrix_b
        
    else: 
            raise TypeError("Argument 'add_or_multiply' must be 'add' or 'multiply'")
            
""" 

The function returns a calculation of two matrices using either addition or multiplication 

The first two input arguments must be of type 'np.array' and the third argument must either be 'add' for addition or 'mult'
for multiplication

The function verifies if the shapes of the matrices are compatible for the chosen calculation

"""
     
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array ([1, 2])



#Question: B-2A
print(add_mult_matrices(B,-2*A, "add")) #does compute


[[ 0 -4  3]
 [ 0 -2 -4]]


In [65]:
#Question: 3C-E
print(add_mult_matrices(3*C, -1*E, "add")) #does not compute
#The matrices does not have the same size

ValueError: Matrices must have the same size

In [66]:
#Question: AC
print(add_mult_matrices(A, C, "multiply")) #does not compute. 
#Matrix A does not have the same amout of columns as matrix C's amount of rows

ValueError: Matrices sizes do not conform for multiplication

In [67]:
#Question CD
print(add_mult_matrices(C, D, "multiply"))

[[11 10]
 [10 11]]


In [68]:
#Question: CB
print(add_mult_matrices(C, B, "multiply"))

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [69]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

#Verify that AB=AC and yet B =! C

print(add_mult_matrices(A, B, "multiply") == add_mult_matrices(A, C, "multiply"))
print(B == C)

[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


**Chap2. Question 3**

In [70]:
A = np.array ([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array ([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print (add_mult_matrices(A, D, "multiply"))
print (add_mult_matrices(D, A, "multiply"))

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [71]:
A = np.array ([[1, -1], [-1, 1]])
B = np.array ([[-1, 1], [1, -1]])

print(add_mult_matrices(A, B, "multiply"))
#rätt svar är a


[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [73]:
A = np.array ([[5, 6], [4, 5]])
B = np.array ([[6, 4], [3, 3]])

A_inv = np.linalg.inv(A)
np.set_printoptions(suppress=True) #linalg.inv computes an inverse and generates a float64 which causes a rounding error  
print ("A inverse:")               #to verify the solution I therefor use np.allclose
print(A_inv)                        
print()
print(np.allclose(A @ A_inv, np.eye(2)))   #np.eye(2) used for Identity matrix with 2 rows, 2 columns
print()

B_inv = np.linalg.inv(B)
print ("B-inverse:")
print(B)
print()
print(np.allclose(B @ B_inv, np.eye(2)))



A inverse:
[[ 5. -6.]
 [-4.  5.]]

True

[[ 1.  0.]
 [-0.  1.]]
B-inverse:
[[6 4]
 [3 3]]

True


**Quiz p.19, Question 3**

In [40]:
A = np.array ([[2, 2], [1, 2]])
print (np.linalg.inv(A)) #rätt svar är "a"

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [35]:
a = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])

x = np.linalg.solve(a, b)
print(x)

print(np.allclose(np.dot(a, x), b)) #verifying that the solution is correct

[ 3.  4. -6.]
True


**Chap10. Question 1 b)**

In [36]:
a = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

x = np.linalg.solve(a, b)
print(y)
print(np.allclose(np.dot(a, x), b)) #verifying that the solution is correct 

[ 8.  2. -1.]
True


**Chap 12. Question 1**

In [39]:
A = ([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
A_inv = np.linalg.inv(A)

print (A_inv)
print(np.allclose(A @ A_inv, np.eye(3))) #Verifying that the answer is correct 
                                         #ie A @ A_inv = I. np.eye(3) used for Identity matrix with 3 rows, 3 columns

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [43]:
v1 = np.arange(4)
v2 = v1[-2:]
v2 [-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [44]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base) #this is a copy since the base attribute returns None
print(v2.base) #this is a view since the base attribute returns the original array

None
[  0   1   2 123]


In [45]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [60]:
v1[0] = 22 #here I see that the first element did NOT change in v2 when i changed it in v1 because v1 is a copy
print(v1)
print(v2)

[ 22   1   2 123]
[  2 123]
